services:
  api:
    # TODO: remove this `build` option when we start supporting specific versions of images
    build: .
    ports:
      - "5000:5000"
    environment:
      - EARTHDATA_APP_USERNAME=${EARTHDATA_APP_USERNAME:?EARTHDATA_APP_USERNAME
        must be set}
      - EARTHDATA_APP_PASSWORD=${EARTHDATA_APP_PASSWORD:?EARTHDATA_APP_PASSWORD
        must be set}
      - EARTHDATA_APP_CLIENT_ID=${EARTHDATA_APP_CLIENT_ID:?EARTHDATA_APP_CLIENT_ID
        must be set}
      - DAT_FLASK_SECRET_KEY=${DAT_FLASK_SECRET_KEY:?DAT_FLASK_SECRET_KEY must
        be set}
    networks:
      - dat
    dns_search: .

  server:
    ports:
      - "443:443"
      - "80:80"
    networks:
      - dat
    dns_search: .

networks:
  dat:
