services:
  api:
    build: .
    volumes:
      - "./src:/tmp/"
      - ./logs/api:/tmp/logs/
    command: '/bin/bash -c "PYTHONPATH=./ python dat_backend/dev_server.py"'

  server:
    build: ./nginx
    user: ""
    volumes:
      - ./logs/server:/var/log/nginx/
