services:
  api:
    ports:
      - "5000:5000"
    environment:
      - EARTHDATA_APP_USERNAME=${EARTHDATA_APP_USERNAME:?EARTHDATA_APP_USERNAME
        must be set}
      - EARTHDATA_APP_PASSWORD=${EARTHDATA_APP_PASSWORD:?EARTHDATA_APP_PASSWORD
        must be set}
      - EARTHDATA_APP_CLIENT_ID=${EARTHDATA_APP_CLIENT_ID:?EARTHDATA_APP_CLIENT_ID
        must be set}
      - DAT_FLASK_SECRET_KEY=${DAT_FLASK_SECRET_KEY:?DAT_FLASK_SECRET_KEY must
        be set}
    networks:
      - dat
    dns_search: .
    restart: always
    volumes:
      - ${LOGS_SHARE_PATH:?LOGS_SHARE_PATH must be set}/api:/tmp/logs/

  server:
    ports:
      - "443:443"
      - "80:80"
    networks:
      - dat
    dns_search: .
    restart: always
    # Setting the user explicitly ensures that the logs are written out as vagrant.
    user: "vagrant:vagrant"
    volumes:
      - ${LOGS_SHARE_PATH:?LOGS_SHARE_PATH must be set}/server:/var/log/nginx/

networks:
  dat:
