services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - EARTHDATA_APP_USERNAME
      - EARTHDATA_APP_PASSWORD
      - EARTHDATA_APP_CLIENT_ID
      - DAT_FLASK_SECRET_KEY
    networks:
      - dat
    dns_search: .

  nginx:
    build: ./nginx
    ports:
      - "443:443"
      - "80:80"
    networks:
      - dat
    dns_search: .

networks:
  dat:
