services:
  api:
    ports:
      - "5000:5000"
    environment:
      - EARTHDATA_APP_USERNAME=${EARTHDATA_APP_USERNAME:?EARTHDATA_APP_USERNAME
        must be set}
      - EARTHDATA_APP_PASSWORD=${EARTHDATA_APP_PASSWORD:?EARTHDATA_APP_PASSWORD
        must be set}
      - EARTHDATA_APP_CLIENT_ID=${EARTHDATA_APP_CLIENT_ID:?EARTHDATA_APP_CLIENT_ID
        must be set}
      - DAT_FLASK_SECRET_KEY=${DAT_FLASK_SECRET_KEY:?DAT_FLASK_SECRET_KEY must
        be set}
    networks:
      - dat
    dns_search: .
    restart: always
    volumes:
      # live logs written directly by the nginx server
      - "./logs/server:/tmp/server_logs/live/:ro"
      # backup logs rotated onto NFS
      - "${LOGS_SHARE_PATH:?LOGS_SHARE_PATH must be
        set}/server:/tmp/server_logs/backup/:ro"

  server:
    ports:
      - "443:443"
      - "80:80"
    networks:
      - dat
    dns_search: .
    restart: always
    # Setting the user explicitly ensures that the logs are written out as vagrant.
    user: "vagrant:vagrant"
    volumes:
      - ./logs/server:/var/log/nginx/

networks:
  dat:
