services:
  api:
    build: .
    volumes:
      - "./src:/tmp/"
      - "./logs/server:/tmp/server_logs:ro"
    command: '/bin/bash -c "PYTHONPATH=./ python dat_backend/dev_server.py"'

  server:
    build: ./nginx
    # In dev, just write out the logs as root. This lets us test/develop on
    # systems that are not owned by `vagrant`, which is what we expect in all
    # NSIDC VM-hosted apps
    user: ""
    volumes:
      - ./logs/server:/var/log/nginx/
