services:
  # TODO: rename this.
  downloader-script:
    # TODO: dev stuff extracted to dev env yaml
    build: .
    ports:
      # - "80:5000"
      # - "443:5000"
      - "5000:5000"
    volumes:
      - "./src:/tmp/"
    environment:
      - EARTHDATA_APP_USERNAME
      - EARTHDATA_APP_PASSWORD
      - EARTHDATA_APP_CLIENT_ID
    networks:
      - dat
    dns_search: .

  nginx:
    build: ./nginx
    ports:
      - "443:443"
      - "80:80"
    networks:
      - dat
    dns_search: .
    volumes:
      - ./nginx/logs:/var/log/nginx/

networks:
  dat:
