# TODO/NOTE: this compose file is identical to the `dev` compose file, except that
# the `user` is set to `":" in the server configuration, so that logs can be
# written to disk.
# Ideally, this overrides the `dev` compose file with only the necessary bit so
# that we do not duplicate so much configuration, but for now this works with
# the `override` symlink approach (rather than needing to pass multiple `-f` to
# compose commands).
services:
  api:
    build: .
    volumes:
      - "./src:/tmp/"
      # live logs written directly by the nginx server
      - "./logs/server:/tmp/server_logs/live/:ro"
    command: '/bin/bash -c "PYTHONPATH=./ python dat_backend/dev_server.py"'

  server:
    build: ./nginx
    volumes:
      - ./logs/server:/var/log/nginx/
    # Run server as root locally. This works for systems that do not have the
    # `vagrant` user defined
    user: ":"
