name: dat-downloader-script-service
channels:
  - conda-forge
  - nsidc
  - nodefaults
dependencies:
  - python ~=3.12.0
  - pydantic ~=2.7.3
  - flask ~=2.3.3
  - flask-restx ~=1.3.0
  - gunicorn ~=22.0

  # Dev deps
  - pytest ~=8.2
  - pyopenssl  # required for test server w/ ssl
