project:
  type: website

website:
  title: "Data Access Tool Backend Documentation"
  site-url: "https://nsidc.github.io/data-access-tool-backend"
  repo-url: &repo-url "https://github.com/nsidc/data-access-tool-backend"
  repo-actions: ["edit", "issue"]
  navbar:
    left:
      - href: getting_started.md
        text: "Getting Started"
      - href: architecture.md
        text: "Architecture"
      - href: testing.md
        text: "Testing"
      - href: developing_with_edd.qmd
        text: "Developing with EDD"
      - href: envvars.md
      - href: logs.md
      - href: releasing.md
      - href: docs.md
        text: "Docs"
      - href: cires_rendezvous_poster.md
        text: "CIRES Rendezvous 2025 poster"
      - href: dat_nsidc_demo_slides.qmd
        text: "NSIDC DAT Demo Slides"

  page-footer:
    left: "© NSIDC 2025"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
