name: "Build and publish container image"

on:
  push:
    branches:
      - "main"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build-and-release-server-image:
    name: "Build and release server container image"
    runs-on: "ubuntu-latest"
    env:
      IMAGE_NAME: "data-access-tool-server"
      # GitHub Actions expressions don't have great conditional support, so
      # writing a ternary expression looks a lot like bash. In Python, this
      # would read as:
      #     github.ref_name if github.ref_type == 'tag' else 'latest'
      #     https://docs.github.com/en/actions/learn-github-actions/expressions
      IMAGE_TAG:
        "${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"

      - name: "Build container image"
        run: |
          docker build --tag "ghcr.io/nsidc/${IMAGE_NAME}:${IMAGE_TAG}" nginx/

      - name: "GHCR login"
        uses: "docker/login-action@v3"
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Push to image registries (DockerHub, GHCR)"
        run: |
          # Push to GHCR
          docker push "ghcr.io/nsidc/${IMAGE_NAME}:${IMAGE_TAG}"
